title: Daray Molden's Portfolio
description: A portfolio showcasing projects, development skills, and my tech journey.
baseurl: ""
url: "https://Daray-dev.github.io"

# Author information
author:
  name: Daray Molden
  email: raymaws1@gmail.com

# Plugins
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections and posts
collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/

# Exclude certain files from the build
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

# Other custom configurations
paginate: 5
